baseURL = "https://delley.github.io/"
title = "Textículos"
theme = "hugo-coder"
defaultContentLanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

disqusShortname = "texticulos-1"

[languages]
  [languages.pt-br]
    languageName = "Português"
    languageCode = "pt-BR"
    weight = 1

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    author = "Francisco Oliveira"
    info = "Analista Desenvolvedor Especialista @ Engineering & entusiasta Go :="
    description = "Pequenos textos sobre coisas diversas, em especial tecnologia"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"
    images = ["images/avatar.jpg"]
    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"
    footercontent = "Textículos: Pequenos textos."
    hidecredits = false
    hidecopyright = false
    rtl = false
    math = true
    dateFormat = "02 de Jan de 2006"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/delley/"

[[params.social]]
name = "X"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://x.com/delley_fx"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/francisco-oliveira/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 4
url = "/index.xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Sobre"
    weight = 2
    url = "/about/"

